# Generated by Django 5.0.1 on 2024-09-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('lyrics', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('countries', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('artist', 'title')},
            },
        ),
    ]
